### ISSUE TITLE
compilation fails due to missing tantivy crate feature

### ISSUE THREAD

**Issue by Fiedzia** [tantivy-search/tantivy-py#13]
error: enum variants on type aliases are experimental
   --> /home/maciej/.cargo/git/checkouts/tantivy-cd4bdf03c5df22c3/cde9b78/src/directory/footer.rs:104:13
    |
104 |             Self::V0(crc) => {
    |             ^^^^^^^^^^^^^
    |
    = help: add `#![feature(type_alias_enum_variants)]` to the crate attributes to enable

I am not sure if I should report it with tantivy
Following the advice works.

**Comment by poljar** [comment]
No need to report it to tantivy, we're tracking tantivy master for now as the latest release is missing some required by the python bindings. I'll add the feature flag.

Thanks for the report.

**Comment by fulmicoton** [comment]
Fixed in tantivy master. No need to add any feature flag because of tantivy ever. Tantivy is supposed to work on rust stable. If it is does not, either this is an issue on tantivy side or you just need to update your rustc
