### ISSUE TITLE
Please support PreTokenized String

### ISSUE THREAD

**Issue by snakeztc** [tantivy-search/tantivy-py#27]
How can I add pre tokenized string using the library? It seems doesn't support add such data type.

**Comment by slckl** [comment]
Assuming that your custom tokenizer outputs a string of tokens, where tokens are split by whitespace, you can  define a custom "tokenizer" based on the built-in SimpleTokenizer, which splits on whitespace and punctuation only.

Something like this, when building your index:
```Rust
use tantivy::tokenizer::{LowerCaser, RemoveLongFilter, SimpleTokenizer, TextAnalyzer};
use tantivy::{Document, Index};

fn register_custom_tokenizer(index: &Index) {
    let custom = TextAnalyzer::from(SimpleTokenizer)
        .filter(RemoveLongFilter::limit(40)) // tantivy default, removes tokens longer than this, remove if unwanted
        .filter(LowerCaser); // also default, remove if you've already done this
    index.tokenizers().register("custom", custom);
}
```

Then, when building schema:
```Rust
use tantivy::schema::*;

let mut schema_builder = Schema::builder();
let text_options = TextOptions::default()
    .set_indexing_options(
        TextFieldIndexing::default()
            .set_tokenizer("custom")
            .set_index_option(IndexRecordOption::WithFreqsAndPositions),
    )
    .set_stored();
schema_builder.add_text_field("custom_field", text_options);
let schema = schema_builder.build()
```

If you use something other than whitespace to define the boundaries between tokens, then you'll have to write a custom tantivy "tokenizer" to split on them, but that should be easy enough.

**Comment by fulmicoton** [comment]
@slckl PretokenizedString is a feature of tantivy already. I suspect @snakeztc is about exposing the functionality in tantivy-py.

**Comment by slckl** [comment]
Yes, sorry about spamming, didn't notice this is a different project :facepalm:

**Comment by fulmicoton** [comment]
@snakeztc I have not tried it, but you can probably get it to work by using `IndexWriter::add_json`. 

The format tantivy accepts is as follows:

 {
        "title":[{
            "text":"The Old Man",
            "tokens":[
                {"offset_from":0,"offset_to":3,"position":0,"text":"The","position_length":1},
                {"offset_from":4,"offset_to":7,"position":1,"text":"Old","position_length":1},
                {"offset_from":8,"offset_to":11,"position":2,"text":"Man","position_length":1}
            ]
        }]
    }
```

**Comment by snakeztc** [comment]
@fulmicoton thanks! I will try this way,
