### ISSUE TITLE
Add a CI pipeline

### ISSUE THREAD

**Issue by petr-tik** [tantivy-search/tantivy-py#5]
Happy to take this. Please assign me to the ticket

- [x] Add a travis script 
- [ ] add a badge to readme to establish trust with potential users

**Comment by poljar** [comment]
So I started  hacking on this and I wrote a travis script based on the [fastuuid](https://github.com/thedrow/fastuuid/) one.

I sadly do not have sufficient permissions to activate the travis build, @fulmicoton could you enable the build or give me permissions to do it myself?

**Comment by fulmicoton** [comment]
Added to [travis](https://travis-ci.org/tantivy-search/tantivy-py)
You are now admin as well.

**Comment by poljar** [comment]
Thanks.
