### ISSUE TITLE
Stay on par with tantivy crates.io version

### ISSUE THREAD

**Issue by petr-tik** [tantivy-search/tantivy-py#6]
The setup file lists version as "0.9.1"

https://github.com/tantivy-search/tantivy-py/blob/master/setup.py#L11

while the core tantivy is on "0.10.1"
https://github.com/tantivy-search/tantivy/blob/master/Cargo.toml#L3

I think it's best if we stick to keeping version numbers the same to make API usage and debugging consistent.

**Comment by poljar** [comment]
If we're going to switch to py03-pack the setup.py file will be gone, I'm assuming that's what you meant with #4. Should then the version in the Cargo.toml be the same as tantivy?

**Comment by petr-tik** [comment]
hey, thanks. That's a good question. 

I think so, while consistency is important, I don't feel that we can break backwards compatibility, so it's best to stay on the same version as core tantivy and publish wheels (TODO) respectively.
